config/routes.rb
Rails.application.routes.draw do
  root 'static_billboards#home'
  
  resources :billboards do
    resources :songs
  end

  resources :artists do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
    has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :billboard, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, except: [:index, :new, :create]

  def index
    @artists = Artist.all
  end

  def show
    @songs = @artist.songs
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to artists_path
    else
      render :edit
    end
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy]
  
  def index
    @billboards = Billboard.all
  end

  def show
    @songs = @billboard.songs.all
  end

  def edit
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboard_path(@billboard)
    else
      render :edit
    end
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else 
      render :new
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private
  def billboard_params
    params.require(:billboard).permit(:charts)
  end

  def set_billboard
    @billboard = Billboard.find(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :song_called

  def index
    @songs = @song_called.songs.all
  end

  def show
  end

  def edit
  end

  def update
  end

  def new
    @song = @billboard.songs.new
  end

  def create
    @song = @billboard.songs.new(song_params)
    if @song.save
      redirect_to billboard_songs_path(@billboard)
    else
      render :new
    end
  end

  def destroy
    @Song.destroy
    redirect_to billboards_path
  end

  protected
  def song_called
    @song_called ||=
    if params[:billboard_id]
      Billboard.find(params[:billboard_id])
    else params[:artist_id]
      Artist.find(params[:artist_id])
    end
  end

  private
  def song_params
    params.require(:song).permit(:title, :album)
  end

  def set_billboard
    @billboard = Billboard.find(params[:billboard_id])
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def set_songs
    @song = Song.find(params[:id])
  end
end

app/controllers/static_billboards_controller.rb
class StaticBillboardsController < ApplicationController
  def home
    @songs = Song.all
  end
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1 class="ui header">Artists</h1>
<hr />
<ul>
    <% @artists.each do |a| %>
        <li><%= link_to a.name, artist_songs_path(a) %></li>
    <% end %>
</ul>
<%= link_to "Add new artist", new_artist_path, class: "ui button" %>

app/views/artists/new.html.erb
<hr />
<%= form_for @artist do |a|%>
    <div class="field">
      <%= a.label "New Artist" %><br />
      <br />
      <%= a.text_field :name, required: true, placeholder: "New chart name" %>
    </div>
    <br />
    <br />
    <%= f.submit nil, class: "ui button primary" %>
    <br />
    <br />
  <% end %>

app/views/artists/show.html.erb
<ul>
  <%= @songs.each do |songs| %>
    <li><%= songs.title %></li>
    <li><%= songs.album %></li>
  <% end %>
</ul>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>Billboards</h1>
<hr />
<ul>
    <% @billboards.each do |b| %>
        <li><%= link_to b.charts, billboard_songs_path(b) %></li>
    <% end %>
</ul>
<br />
<%= link_to "Add a new Billboard", new_billboard_path, class: "ui button" %>

app/views/billboards/new.html.erb
<hr />
<%= form_for @billboard do |f|%>
    <div class="field">
      <%= f.label "New Billboard Chart" %><br />
      <br />
      <%= f.text_field :charts, required: true, placeholder: "New chart name" %>
    </div>
    <br />
    <br />
    <%= f.submit nil, class: "ui button primary" %>
    <br />
    <br />
  <% end %>

app/views/billboards/show.html.erb
<h1><%= @billboard.charts %></h1>

<ul>
  <%= @songs.each do |songs| %>
    <li><%= songs.title %></li>
    <li><%= songs.album %></li>
  <% end %>
</ul>

app/views/layouts/_navbar.html.erb
<%= link_to 'Billboards', billboards_path %>
<%= link_to 'Artists', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBillboards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="ui container">
    <%= render 'layouts/navbar' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1> Songs </h1>
<hr />

<ul>
  <% @songs.each do |songs| %>
    <li><%= songs.title %></li>
    <li><%= songs.album %></li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<hr />
<%= form_for @song do |s| %>
    <div class="field">
        <%= s.label :title %><br />
        <%= s.text_field :title, required: true, autofocus: true, placeholder: "Song Title" %>
        <br />
        <%= s.label :album %><br />
        <%= s.text_field :album, placeholder: "Album" %>
    </div>
    <br />
    <%= f.submit nil, class: "ui button primary" %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>

<ul>
  <%= @songs.each do |songs| %>
    <li><%= songs.title %></li>
    <li><%= songs.album %></li>
  <% end %>
</ul>

app/views/static_billboards/home.html.erb
<h1> Top Billboard Songs </h1>

<ul>
<% @songs.each do |songs| %>
  <li><%= songs.title %></li>
  <li><%= songs.album %></li>
<% end %>
</ul>